name: Build & Push Docker image

on:
  push:
    branches: [main]

jobs:
  build-push:
    runs-on: ubuntu-latest
    environment: portfolio 
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: nolansr13/essertaize-portfolio:latest

   
  deploy:
      runs-on: self-hosted
      needs: build-push
      environment: portfolio
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      steps:
        - name: SSH Deploy to Tailscale server
          uses: appleboy/ssh-action@v0.1.7
          with:
            host: nolanserver
            username: sr13
            key: ${{ secrets.SERVER_SSH_KEY }}
            envs: GOOGLE_API_KEY
            script: |
              docker pull nolansr13/essertaize-portfolio
              docker stop essertaize-portfolio || true
              docker rm essertaize-portfolio || true
              docker run -d --name essertaize-portfolio -p 3000:3000 -e GOOGLE_API_KEY="$GOOGLE_API_KEY" nolansr13/essertaize-portfolio:latest
